# Prefix
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

unbind C-a
set -g prefix2 C-a
bind C-a send-prefix -2

set -g base-index 1

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

bind n display-panes
bind : command-prompt

bind c copy-mode

setw -g mode-keys vi

# Scroll up and down
bind -T copy-mode-vi n send-keys -X halfpage-down
bind -T copy-mode-vi p send-keys -X halfpage-up

# Visual mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

bind s choose-session

# Pane
bind v split-window -h
unbind x
bind x split-window -v
bind o rotate-window
bind q kill-pane

# Change focus around panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Swap panes
bind -r C-h swap-pane -D
bind -r C-j swap-pane -U
bind -r C-k swap-pane -D
bind -r C-l swap-pane -U

# Resize panes
bind -r i resize-pane -U 5
bind -r u resize-pane -D 5
bind -r y resize-pane -L 5
bind -r o resize-pane -R 5

# Window
bind Enter new-window
unbind .
unbind ,
bind -n C-. next-window
bind -n C-, previous-window
