local nmap = require("util.keymaps").n

local snacks = require("snacks")

nmap("<leader><leader>", function() snacks.picker.smart() end)
nmap("<leader>,", function() snacks.picker.buffers() end)
nmap("<leader>/", function() snacks.picker.grep() end)
nmap("<leader>:", function() snacks.picker.command_history() end)
nmap("<leader>n", function() snacks.picker.notifications() end)
nmap("<leader>e", function() snacks.explorer() end)

nmap("<leader>fb", function() snacks.picker.buffers() end)
nmap("<leader>fc", function() snacks.picker.files({ cwd = vim.fn.stdpath("config") }) end)
nmap("<leader>ff", function() snacks.picker.files() end)
nmap("<leader>fg", function() snacks.picker.git_files() end)
nmap("<leader>fp", function() snacks.picker.projects() end)
nmap("<leader>fr", function() snacks.picker.recent() end)

nmap("<leader>gb", function() snacks.picker.git_branches() end)
nmap("<leader>gl", function() snacks.picker.git_log() end)
nmap("<leader>gL", function() snacks.picker.git_log_line() end)
nmap("<leader>gs", function() snacks.picker.git_status() end)
nmap("<leader>gS", function() snacks.picker.git_stash() end)
nmap("<leader>gd", function() snacks.picker.git_diff() end)
nmap("<leader>gf", function() snacks.picker.git_log_file() end)

nmap("<leader>sb", function() snacks.picker.lines() end)
nmap("<leader>sB", function() snacks.picker.grep_buffers() end)
nmap("<leader>sg", function() snacks.picker.grep() end)
nmap("<leader>sw", function() snacks.picker.grep_word() end)

nmap('<leader>s"', function() snacks.picker.registers() end)
nmap("<leader>s/", function() snacks.picker.search_history() end)
nmap("<leader>sa", function() snacks.picker.autocmds() end)
nmap("<leader>sb", function() snacks.picker.lines() end)
nmap("<leader>sc", function() snacks.picker.command_history() end)
nmap("<leader>sC", function() snacks.picker.commands() end)
nmap("<leader>sd", function() snacks.picker.diagnostics() end)
nmap("<leader>sD", function() snacks.picker.diagnostics_buffer() end)
nmap("<leader>sh", function() snacks.picker.help() end)
nmap("<leader>sH", function() snacks.picker.highlights() end)
nmap("<leader>si", function() snacks.picker.icons() end)
nmap("<leader>sj", function() snacks.picker.jumps() end)
nmap("<leader>sk", function() snacks.picker.keymaps() end)
nmap("<leader>sl", function() snacks.picker.loclist() end)
nmap("<leader>sm", function() snacks.picker.marks() end)
nmap("<leader>sM", function() snacks.picker.man() end)
nmap("<leader>sp", function() snacks.picker.lazy() end)
nmap("<leader>sq", function() snacks.picker.qflist() end)
nmap("<leader>sR", function() snacks.picker.resume() end)
nmap("<leader>su", function() snacks.picker.undo() end)
nmap("<leader>uC", function() snacks.picker.colorschemes() end)

nmap("gd", function() snacks.picker.lsp_definitions() end)
nmap("gD", function() snacks.picker.lsp_declarations() end)
nmap("gr", function() snacks.picker.lsp_references() end)
nmap("gI", function() snacks.picker.lsp_implementations() end)
nmap("gy", function() snacks.picker.lsp_type_definitions() end)
nmap("<leader>ss", function() snacks.picker.lsp_symbols() end)
nmap("<leader>sS", function() snacks.picker.lsp_workspace_symbols() end)

nmap("<leader>z", function() snacks.zen() end)
nmap("<leader>Z", function() snacks.zen.zoom() end)
nmap("<leader>.", function() snacks.scratch() end)
nmap("<leader>S", function() snacks.scratch.select() end)
nmap("<leader>n", function() snacks.notifier.show_history() end)
nmap("<leader>bd", function() snacks.bufdelete() end)
nmap("<leader>cR", function() snacks.rename.rename_file() end)
nmap("<leader>gB", function() snacks.gitbrowse() end)
nmap("<leader>gg", function() snacks.lazygit() end)
nmap("<leader>un", function() snacks.notifier.hide() end)
